name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: make_compile_commands.json
        run: |
          ls
          git clone https://github.com/ryuichiueda/ros_setup_scripts_Ubuntu18.04_server.git
          cd  ros_setup_scripts_Ubuntu18.04_server
          bash step0.bash
          bash step1.bash
          cd ..
          source /opt/ros/melodic/setup.bash
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON


      - name: Generate compile_commands.json
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{github.workspace}}/CMakeLists.txt'
          useVcpkgToolchainFile: true
          # has to be the github workspace, not the runner workspace, for the docker-based clang-tidy-review
          buildDirectory: '${{github.workspace}}/build'
          cmakeAppendedArgs: >-
            -DCMAKE_GLOBAL_AUTOGEN_TARGET=ON
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      # Optionally generate compile_commands.json

      - uses: ZedThree/clang-tidy-review@v0.6.0
        id: review
        with:
          build_dir: 'build'
      # If there are any comments, fail the check
      - name: Passed C++ style guide checks
        if: steps.review.outputs.total_comments > 0
        run: exit 1