name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: make_compile_commands.json
        run: |
          ls
          git clone https://github.com/ryuichiueda/ros_setup_scripts_Ubuntu18.04_desktop.git
          cd  ros_setup_scripts_Ubuntu18.04_desktop
          bash step0.bash
          bash step1.bash
          cd ..
          rm -rf ros_setup_scripts_Ubuntu18.04_desktop
          rosdep install -r -y --from-paths --ignore-src ./
          sudo apt install bear
          source /opt/ros/melodic/setup.bash
          cmake .
          bear make

      - uses: ZedThree/clang-tidy-review@v0.6.0
        id: review
      # If there are any comments, fail the check
      - name: Passed C++ style guide checks
        if: steps.review.outputs.total_comments > 0
        run: exit 1