name: clang-tidy-review

# You can be more specific, but it currently only works on pull requests
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: make_compile_commands.json
        run: |
          ls
          git clone https://github.com/ryuichiueda/ros_setup_scripts_Ubuntu18.04_server.git
          cd  ros_setup_scripts_Ubuntu18.04_server
          bash step0.bash
          bash step1.bash
          cd ..
          source /opt/ros/melodic/setup.bash
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      
      - uses: actions/checkout@v2

      # Optionally generate compile_commands.json

      - uses: ZedThree/clang-tidy-review@v0.6.0
        id: review
      # If there are any comments, fail the check
      - if: steps.review.outputs.total_comments > 0
        run: exit 1